-- MySQL Script generated by MySQL Workbench
-- Wed Mar 19 23:23:18 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cine
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_cine` ;

-- -----------------------------------------------------
-- Schema db_cine
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cine` DEFAULT CHARACTER SET utf8 ;
USE `db_cine` ;

-- -----------------------------------------------------
-- Table `db_cine`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`usuario` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`usuario` (
  `idusuario` INT NOT NULL,
  `nombre` VARCHAR(150) NULL,
  `email` VARCHAR(45) NULL,
  `contraseña` VARCHAR(45) NULL,
  `rol` ENUM("cliente, cajero, administrador") NULL,
  `usuariocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cine`.`salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`salas` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`salas` (
  `idsalas` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `capacidad_filas` INT NULL,
  `capacidad_col` INT NULL,
  `capacidad_t` INT NULL,
  PRIMARY KEY (`idsalas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cine`.`peliculas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`peliculas` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`peliculas` (
  `idpelicula` INT NOT NULL,
  `titulo` VARCHAR(100) NULL,
  `poster` VARCHAR(255) NULL,
  `duracion` INT NOT NULL,
  `descripcion` TEXT(300) NULL,
  `clasificacion` VARCHAR(20) NULL,
  `genero` VARCHAR(50) NULL,
  PRIMARY KEY (`idpelicula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cine`.`funcion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`funcion` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`funcion` (
  `idfunciones` INT NOT NULL,
  `horario` DATETIME NULL,
  `peliculas_idpelicula` INT NOT NULL,
  `salas_idsalas` INT NOT NULL,
  `precio` FLOAT NULL,
  `estado` ENUM("programada, en curso, finalizado") NULL,
  PRIMARY KEY (`idfunciones`),
  CONSTRAINT `fk_funciones_peliculas1`
    FOREIGN KEY (`peliculas_idpelicula`)
    REFERENCES `db_cine`.`peliculas` (`idpelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funciones_salas1`
    FOREIGN KEY (`salas_idsalas`)
    REFERENCES `db_cine`.`salas` (`idsalas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_funciones_peliculas1_idx` ON `db_cine`.`funcion` (`peliculas_idpelicula` ASC) VISIBLE;

CREATE INDEX `fk_funciones_salas1_idx` ON `db_cine`.`funcion` (`salas_idsalas` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_cine`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`reserva` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`reserva` (
  `idreservaciones` INT NOT NULL,
  `estado` ENUM("Finalizado, en curso") NULL,
  `usuario_idusuario` INT NOT NULL,
  `funciones_idfunciones` INT NOT NULL,
  `asientos` VARCHAR(45) NULL,
  `precioTotal` FLOAT NULL,
  PRIMARY KEY (`idreservaciones`),
  CONSTRAINT `fk_reservaciones_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `db_cine`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservaciones_funciones1`
    FOREIGN KEY (`funciones_idfunciones`)
    REFERENCES `db_cine`.`funcion` (`idfunciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_reservaciones_usuario1_idx` ON `db_cine`.`reserva` (`usuario_idusuario` ASC) VISIBLE;

CREATE INDEX `fk_reservaciones_funciones1_idx` ON `db_cine`.`reserva` (`funciones_idfunciones` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `db_cine`.`asientos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_cine`.`asientos` ;

CREATE TABLE IF NOT EXISTS `db_cine`.`asientos` (
  `idasientos` INT NOT NULL,
  `fila` INT NULL,
  `columna` INT NULL,
  `reservaciones_idreservaciones` INT NOT NULL,
  `estado` ENUM("Disponible, reservado, ocupado") NULL,
  `funciones_idfunciones` INT NOT NULL,
  PRIMARY KEY (`idasientos`),
  CONSTRAINT `fk_asientos_reservaciones1`
    FOREIGN KEY (`reservaciones_idreservaciones`)
    REFERENCES `db_cine`.`reserva` (`idreservaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asientos_funciones1`
    FOREIGN KEY (`funciones_idfunciones`)
    REFERENCES `db_cine`.`funcion` (`idfunciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_asientos_reservaciones1_idx` ON `db_cine`.`asientos` (`reservaciones_idreservaciones` ASC) VISIBLE;

CREATE INDEX `fk_asientos_funciones1_idx` ON `db_cine`.`asientos` (`funciones_idfunciones` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
